name: hu_library_app
description: "Hashemite University Library App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # --- Firebase ---
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.1

  # --- State Management ---
  provider: ^6.1.1

  # --- Navigation ---
  go_router: ^12.1.1

  # --- Localization ---
  easy_localization: ^3.0.0
  intl: any

  # --- UI ---
  flutter_svg: ^2.0.10

  # --- Utils ---
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/book_suggestion.png
    - assets/images/donate_book.png
    - assets/images/hall.png
    - assets/images/reserved.png
    - assets/images/room1.jpg
    - assets/images/room2.jpg
    - assets/images/room3.jpg
    - assets/translations/