// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'This platform is not configured.',
        );
    }
  }

  // 🌐 Web (تم تصحيحه)
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUp479n0kav5FFQaH2ez4D9uBLyH3wU4o',
    appId: '1:213123490500:web:1147020a3a9e6c078d9f91',
    messagingSenderId: '213123490500',
    projectId: 'hu-library-app',
    authDomain: 'hu-library-app.firebaseapp.com',
    storageBucket: 'hu-library-app.firebasestorage.app',
  );

  // 🤖 Android (زي ما هو من JSON)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjdkfk66NSdCHuYH0g2IhglYo-VTN31Ng',
    appId: '1:213123490500:android:20e8d4c5473006188d9f91',
    messagingSenderId: '213123490500',
    projectId: 'hu-library-app',
    storageBucket: 'hu-library-app.firebasestorage.app',
  );
}