// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDimC8nYuP-5nWDL0iTq_FBJkYu2-uE_dI',
    appId: '1:964215488715:web:3a821e53a4eb9b46581b4e',
    messagingSenderId: '964215488715',
    projectId: 'hashemite-university-library',
    authDomain: 'hashemite-university-library.firebaseapp.com',
    storageBucket: 'hashemite-university-library.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDndLyZc60-pAg6VFob8iH65JoeDg7Ks6Y',
    appId: '1:964215488715:android:9836e0c9cc2a9fa3581b4e',
    messagingSenderId: '964215488715',
    projectId: 'hashemite-university-library',
    storageBucket: 'hashemite-university-library.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrZ3sxQ6rAKxbA7ofHtwbjSPeYate_R5w',
    appId: '1:964215488715:ios:a905b8536cf59c6e581b4e',
    messagingSenderId: '964215488715',
    projectId: 'hashemite-university-library',
    storageBucket: 'hashemite-university-library.firebasestorage.app',
    iosBundleId: 'com.example.huLibraryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrZ3sxQ6rAKxbA7ofHtwbjSPeYate_R5w',
    appId: '1:964215488715:ios:a905b8536cf59c6e581b4e',
    messagingSenderId: '964215488715',
    projectId: 'hashemite-university-library',
    storageBucket: 'hashemite-university-library.firebasestorage.app',
    iosBundleId: 'com.example.huLibraryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDimC8nYuP-5nWDL0iTq_FBJkYu2-uE_dI',
    appId: '1:964215488715:web:12889f2ecc20ac06581b4e',
    messagingSenderId: '964215488715',
    projectId: 'hashemite-university-library',
    authDomain: 'hashemite-university-library.firebaseapp.com',
    storageBucket: 'hashemite-university-library.firebasestorage.app',
  );
}
